<a href="https://colab.research.google.com/github/FathimaNazarudeen/Advanced-Computing-Lab/blob/main/project.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [531]:
# Importing the pandas library as 'pd' for data manipulation and analysis
import pandas as pd
# Importing the numpy library as 'np' for numerical computations
import numpy as np

In [532]:
# Reading the CSV file "train.csv" into a pandas DataFrame named 'df'
df=pd.read_csv("/content/train.csv")

In [533]:
print(df.dtypes)

PassengerId      int64
Survived         int64
Pclass           int64
Name            object
Sex             object
Age            float64
SibSp            int64
Parch            int64
Ticket          object
Fare           float64
Cabin           object
Embarked        object
dtype: object


In [534]:
# Creating a new DataFrame 'data_real' by copying 'df' and replacing infinite values (np.inf) with NaN (Not a Number)
data_real = df.replace(np.inf, np.nan)

In [535]:
# Calculate the mean of each numeric column in the 'data_real' DataFrame
mean_values = data_real.mean(numeric_only=True)

In [536]:
# Fill the missing values in 'data_real' DataFrame with the corresponding mean of each numeric column
data_real_filled = data_real.fillna(mean_values)

In [537]:
# Fill the remaining missing values in non-numeric columns with the most frequent value in each column
data_real_filled = data_real_filled.apply(lambda col: col.fillna(col.value_counts().idxmax()))

In [538]:
# Calculate the total number of missing values in the 'data_real_filled' DataFrame after filling
total_missing = data_real_filled.isnull().sum().sum()
# Print the total number of missing values after filling
print("Total missing values after filling:", total_missing)

Total missing values after filling: 0


In [539]:
data_real_filled

PassengerId  Survived  Pclass  \
0              1         0       3   
1              2         1       1   
2              3         1       3   
3              4         1       1   
4              5         0       3   
..           ...       ...     ...   
886          887         0       2   
887          888         1       1   
888          889         0       3   
889          890         1       1   
890          891         0       3   

                                                  Name     Sex        Age  \
0                              Braund, Mr. Owen Harris    male  22.000000   
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.000000   
2                               Heikkinen, Miss. Laina  female  26.000000   
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.000000   
4                             Allen, Mr. William Henry    male  35.000000   
..                                                 ...     ...        ...   
886                              Montvila, Rev. Juozas    male  27.000000   
887                       Graham, Miss. Margaret Edith  female  19.000000   
888           Johnston, Miss. Catherine Helen "Carrie"  female  29.699118   
889                              Behr, Mr. Karl Howell    male  26.000000   
890                                Dooley, Mr. Patrick    male  32.000000   

     SibSp  Parch            Ticket     Fare    Cabin Embarked  
0        1      0         A/5 21171   7.2500  B96 B98        S  
1        1      0          PC 17599  71.2833      C85        C  
2        0      0  STON/O2. 3101282   7.9250  B96 B98        S  
3        1      0            113803  53.1000     C123        S  
4        0      0            373450   8.0500  B96 B98        S  
..     ...    ...               ...      ...      ...      ...  
886      0      0            211536  13.0000  B96 B98        S  
887      0      0            112053  30.0000      B42        S  
888      1      2        W./C. 6607  23.4500  B96 B98        S  
889      0      0            111369  30.0000     C148        C  
890      0      0            370376   7.7500  B96 B98        Q  

[891 rows x 12 columns]

In [540]:
# Drop the column 'Embarked' from the DataFrame 'data_real_filled' and store the result in 'data_X'
data_X = data_real_filled.drop(['Embarked'], axis = 1)

In [541]:
# Extract the column 'Embarked' from the DataFrame 'data_real_filled' and store it in 'data_y'
data_y = data_real_filled['Embarked']

Label encoding

In [542]:
# Import the LabelEncoder from scikit-learn to perform label encoding
from sklearn.preprocessing import LabelEncoder

# Create an instance of LabelEncoder
le = LabelEncoder()

In [543]:
# Perform label encoding on 'data_y' to convert categorical values to numerical labels
data_y_trans = le.fit_transform(data_y)
# The transformed 'data_y_trans' now contains numeric labels for the 'Embarked' column, and it is ready to be used in machine learning models that require numerical inputs for the target variable.

In [544]:
data_y_trans

array([2, 0, 2, 2, 2, 1, 2, 2, 2, 0, 2, 2, 2, 2, 2, 2, 1, 2, 2, 0, 2, 2,
       1, 2, 2, 2, 0, 2, 1, 2, 0, 0, 1, 2, 0, 2, 0, 2, 2, 0, 2, 2, 0, 0,
       1, 2, 1, 1, 0, 2, 2, 2, 0, 2, 0, 2, 2, 0, 2, 2, 0, 2, 2, 2, 0, 0,
       2, 2, 2, 2, 2, 2, 2, 0, 2, 2, 2, 2, 2, 2, 2, 2, 1, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 0, 0, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 1,
       2, 0, 2, 2, 0, 2, 1, 2, 0, 2, 2, 2, 0, 2, 2, 0, 1, 2, 0, 2, 0, 2,
       2, 2, 2, 0, 2, 2, 2, 0, 0, 2, 2, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 0, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 1, 2, 2, 0, 2,
       2, 0, 2, 2, 2, 0, 2, 2, 2, 2, 1, 2, 1, 2, 2, 2, 2, 2, 0, 0, 1, 2,
       1, 2, 2, 2, 2, 0, 2, 2, 2, 0, 1, 0, 2, 2, 2, 2, 1, 0, 2, 2, 0, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 0, 1,
       2, 2, 0, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 0, 0, 2, 0, 2, 1, 2, 2, 2,
       1, 2, 2, 2, 2, 2, 2, 2, 2, 0, 1, 2, 2, 2, 1, 2, 1, 2, 2, 2, 2, 0,
       2, 2, 2, 1, 2, 0, 0, 2, 2, 0, 0, 2, 2, 0, 1,

In [545]:
le_name = LabelEncoder()
le_fid.fit(data_X['Name'])
data_X['Name'] = le_fid.fit_transform(data_X['Name'])

In [546]:
le_sex = LabelEncoder()
le_fid.fit(data_X['Sex'])
data_X['Sex'] = le_fid.fit_transform(data_X['Sex'])

In [547]:
le_ticket = LabelEncoder()
le_fid.fit(data_X['Ticket'])
data_X['Ticket'] = le_fid.fit_transform(data_X['Ticket'])

In [548]:
le_cabin = LabelEncoder()
le_fid.fit(data_X['Cabin'])
data_X['Cabin'] = le_fid.fit_transform(data_X['Cabin'])

In [549]:
# 'data_X' now contains the DataFrame with the categorical columns ('Name', 'Sex', 'Ticket', and 'Cabin') replaced by numerical labels obtained through label encoding.
data_X

PassengerId  Survived  Pclass  Name  Sex        Age  SibSp  Parch  \
0              1         0       3   108    1  22.000000      1      0   
1              2         1       1   190    0  38.000000      1      0   
2              3         1       3   353    0  26.000000      0      0   
3              4         1       1   272    0  35.000000      1      0   
4              5         0       3    15    1  35.000000      0      0   
..           ...       ...     ...   ...  ...        ...    ...    ...   
886          887         0       2   548    1  27.000000      0      0   
887          888         1       1   303    0  19.000000      0      0   
888          889         0       3   413    0  29.699118      1      2   
889          890         1       1    81    1  26.000000      0      0   
890          891         0       3   220    1  32.000000      0      0   

     Ticket     Fare  Cabin  
0       523   7.2500     47  
1       596  71.2833     81  
2       669   7.9250     47  
3        49  53.1000     55  
4       472   8.0500     47  
..      ...      ...    ...  
886     101  13.0000     47  
887      14  30.0000     30  
888     675  23.4500     47  
889       8  30.0000     60  
890     466   7.7500     47  

[891 rows x 11 columns]

In [550]:
# Create a new DataFrame 'df2' with the preprocessed features (label encoded columns)
df2 = pd.DataFrame(data_X)


In [551]:
# Save the DataFrame 'df2' to a CSV file named "my_data.csv"
df2.to_csv(r'my_data.csv', index=False)

In [552]:
# Import the 'train_test_split' function from scikit-learn to split the data into training and testing sets
from sklearn.model_selection import train_test_split

# Split the data into training and testing sets with 70% for training and 30% for testing, using a specific random_state (67)
X_train, X_test,y_train, y_test = train_test_split(data_X, data_y_trans, train_size = 0.7,random_state=67)

In [553]:
# Import the 'StandardScaler' class from scikit-learn for feature scaling
from sklearn.preprocessing import StandardScaler

# Create an instance of StandardScaler for feature scaling
ss = StandardScaler()

# Standardize (scale) the training features using 'fit_transform'
X_train_std = ss.fit_transform(X_train)

# Standardize (scale) the testing features using 'transform'
X_test_std = ss.fit_transform(X_test)

In [554]:
# Import metrics for model evaluation
from sklearn.metrics import accuracy_score
from sklearn.metrics import classification_report
from sklearn.metrics import confusion_matrix

Decision Tree

In [555]:
# Import the DecisionTreeClassifier from scikit-learn
from sklearn.tree import DecisionTreeClassifier

# Create an instance of the DecisionTreeClassifier
ml = DecisionTreeClassifier()

# Train the Decision Tree Classifier on the standardized training data
ml.fit(X_train_std, y_train)

# Make predictions on the standardized test data
res = ml.predict(X_test_std)

# Import the accuracy_score metric from scikit-learn
from sklearn.metrics import accuracy_score

# Calculate the accuracy of the model by comparing the predicted labels with the true labels
accuracy_1 = accuracy_score(y_test, res)

# Print the accuracy of the Decision Tree Classifier
print("Decision tree accuracy:", accuracy_1 * 100)

Decision tree accuracy: 76.86567164179104


In [556]:
# Convert the predicted numerical labels (res) and true numerical labels (y_test) back to their original categorical values
# using the inverse_transform method of the LabelEncoder (le).
# Print the classification report, comparing the original categorical values
print("Classification Report for Decision Tree: \n", classification_report(le.inverse_transform(y_test), le.inverse_transform(res)))

Classification Report for Decision Tree: 
               precision    recall  f1-score   support

           C       0.61      0.72      0.66        53
           Q       0.41      0.60      0.49        20
           S       0.88      0.80      0.84       195

    accuracy                           0.77       268
   macro avg       0.64      0.71      0.66       268
weighted avg       0.79      0.77      0.78       268



In [557]:
#Calculate the confusion matrix for the Decision Tree Classifier's predictions
rf_conf_mat = confusion_matrix(y_test, res)
print("Decision Tree: \n", rf_conf_mat)

Decision Tree: 
 [[ 38   1  14]
 [  1  12   7]
 [ 23  16 156]]


Random Forest

In [558]:
# Import the RandomForestClassifier from scikit-learn
from sklearn.ensemble import RandomForestClassifier

# Create an instance of the RandomForestClassifier
rf1 = RandomForestClassifier()

# Train the Random Forest Classifier on the standardized training data
rf1.fit(X_train_std, y_train)

# Make predictions on the standardized test data
rf_y_pred1 = rf1.predict(X_test_std)

# Import the accuracy_score metric from scikit-learn
from sklearn.metrics import accuracy_score

# Calculate the accuracy of the Random Forest Classifier
acc_score1 = accuracy_score(y_test, rf_y_pred1)

# Print the accuracy of the Random Forest Classifier
print("Accuracy Score for Random Forest:", acc_score1 * 100)

Accuracy Score for Random Forest: 86.19402985074626


In [559]:
# Now, print the classification report, comparing the original categorical values
print("Classification Report for Random Forest: \n", classification_report(le.inverse_transform(y_test), le.inverse_transform(rf_y_pred1)))

Classification Report for Random Forest: 
               precision    recall  f1-score   support

           C       0.84      0.70      0.76        53
           Q       1.00      0.25      0.40        20
           S       0.86      0.97      0.91       195

    accuracy                           0.86       268
   macro avg       0.90      0.64      0.69       268
weighted avg       0.87      0.86      0.85       268



In [560]:
# Calculate the confusion matrix for the Random Forest Classifier's predictions
rf_conf_mat = confusion_matrix(y_test, rf_y_pred1)
print("Random Forest Confusion matrix: \n", rf_conf_mat)

Random Forest Confusion matrix: 
 [[ 37   0  16]
 [  1   5  14]
 [  6   0 189]]


Gradient Boosting

In [561]:
# Import the GradientBoostingClassifier from scikit-learn
from sklearn.ensemble import GradientBoostingClassifier

# Create an instance of the GradientBoostingClassifier
gradient_boost1 = GradientBoostingClassifier()

# Train the Gradient Boosting Classifier on the standardized training data
gradient_boost1.fit(X_train_std, y_train)

# Make predictions on the standardized test data
res_xg1 = gradient_boost1.predict(X_test_std)

# Import the accuracy_score metric from scikit-learn
from sklearn.metrics import accuracy_score

# Calculate the accuracy of the Gradient Boosting Classifier
acc_score_xg1 = accuracy_score(y_test, res_xg1)

# Print the accuracy of the Gradient Boosting Classifier
print("Accuracy Score for Gradient Boosting:", acc_score_xg1 * 100)

Accuracy Score for Gradient Boosting: 88.43283582089553


In [562]:
# Now,print the classification report, comparing the original categorical values
print("Classification Report for Gradient Boosting: \n", classification_report(le.inverse_transform(y_test), le.inverse_transform(res_xg1)))

Classification Report for Gradient Boosting: 
               precision    recall  f1-score   support

           C       0.83      0.72      0.77        53
           Q       0.92      0.60      0.73        20
           S       0.89      0.96      0.93       195

    accuracy                           0.88       268
   macro avg       0.88      0.76      0.81       268
weighted avg       0.88      0.88      0.88       268



In [563]:
# Calculate the confusion matrix for the Gradient Boosting Classifier's predictions
rf_conf_mat = confusion_matrix(y_test, res_xg1)
print("Gradient Boosting Confusion matrix: \n", rf_conf_mat)

Gradient Boosting Confusion matrix: 
 [[ 38   1  14]
 [  0  12   8]
 [  8   0 187]]


SVM

In [564]:
# Import the SVC (Support Vector Classifier) from scikit-learn
from sklearn.svm import SVC

# Create an instance of the Support Vector Machine (SVM) classifier
svm_classifier = SVC()

# Train the SVM classifier on the standardized training data
svm_classifier.fit(X_train_std, y_train)

# Make predictions on the standardized test data
res_svm = svm_classifier.predict(X_test_std)

# Import the accuracy_score metric from scikit-learn
from sklearn.metrics import accuracy_score

# Calculate the accuracy of the SVM classifier
acc_score_svm = accuracy_score(y_test, res_svm)

# Print the accuracy of the SVM classifier
print("Accuracy Score for SVM:", acc_score_svm * 100)

Accuracy Score for SVM: 75.3731343283582


In [565]:
# Now, print the classification report, comparing the original categorical values
print("Classification Report for SVM: \n", classification_report(le.inverse_transform(y_test), le.inverse_transform(res_svm)))

Classification Report for SVM: 
               precision    recall  f1-score   support

           C       0.73      0.15      0.25        53
           Q       0.50      0.05      0.09        20
           S       0.76      0.99      0.86       195

    accuracy                           0.75       268
   macro avg       0.66      0.40      0.40       268
weighted avg       0.73      0.75      0.68       268



In [566]:
# Calculate the confusion matrix for the SVM classifier's predictions
svm_conf_mat = confusion_matrix(y_test, res_svm)
print("SVM Confusion Matrix: \n", svm_conf_mat)

SVM Confusion Matrix: 
 [[  8   1  44]
 [  1   1  18]
 [  2   0 193]]
