<a href="https://colab.research.google.com/github/FathimaNazarudeen/Advanced-Computing-Lab/blob/main/project.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [50]:
import pandas as pd
import numpy as np

In [126]:
df=pd.read_csv("/content/train.csv")

In [127]:
print(df.dtypes)

PassengerId      int64
Survived         int64
Pclass           int64
Name            object
Sex             object
Age            float64
SibSp            int64
Parch            int64
Ticket          object
Fare           float64
Cabin           object
Embarked        object
dtype: object


In [128]:
data_real = df.replace(np.inf, np.nan)

In [129]:
mean_values = data_real.mean(numeric_only=True)

In [130]:
data_real_filled = data_real.fillna(mean_values)

In [132]:
data_real_filled = data_real_filled.apply(lambda col: col.fillna(col.value_counts().idxmax()))

In [133]:
total_missing = data_real_filled.isnull().sum().sum()
print("Total missing values after filling:", total_missing)

Total missing values after filling: 0


In [135]:
data_real_filled

PassengerId  Survived  Pclass  \
0              1         0       3   
1              2         1       1   
2              3         1       3   
3              4         1       1   
4              5         0       3   
..           ...       ...     ...   
886          887         0       2   
887          888         1       1   
888          889         0       3   
889          890         1       1   
890          891         0       3   

                                                  Name     Sex        Age  \
0                              Braund, Mr. Owen Harris    male  22.000000   
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.000000   
2                               Heikkinen, Miss. Laina  female  26.000000   
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.000000   
4                             Allen, Mr. William Henry    male  35.000000   
..                                                 ...     ...        ...   
886                              Montvila, Rev. Juozas    male  27.000000   
887                       Graham, Miss. Margaret Edith  female  19.000000   
888           Johnston, Miss. Catherine Helen "Carrie"  female  29.699118   
889                              Behr, Mr. Karl Howell    male  26.000000   
890                                Dooley, Mr. Patrick    male  32.000000   

     SibSp  Parch            Ticket     Fare    Cabin Embarked  
0        1      0         A/5 21171   7.2500  B96 B98        S  
1        1      0          PC 17599  71.2833      C85        C  
2        0      0  STON/O2. 3101282   7.9250  B96 B98        S  
3        1      0            113803  53.1000     C123        S  
4        0      0            373450   8.0500  B96 B98        S  
..     ...    ...               ...      ...      ...      ...  
886      0      0            211536  13.0000  B96 B98        S  
887      0      0            112053  30.0000      B42        S  
888      1      2        W./C. 6607  23.4500  B96 B98        S  
889      0      0            111369  30.0000     C148        C  
890      0      0            370376   7.7500  B96 B98        Q  

[891 rows x 12 columns]

In [154]:
data_X = data_real_filled.drop(['Embarked'], axis = 1)

In [155]:
data_y = data_real_filled['Embarked']

Label encoding

In [156]:

from sklearn.preprocessing import LabelEncoder


le = LabelEncoder()

In [157]:
data_y_trans = le.fit_transform(data_y)
le_fid = LabelEncoder()

In [158]:
data_y_trans

array([2, 0, 2, 2, 2, 1, 2, 2, 2, 0, 2, 2, 2, 2, 2, 2, 1, 2, 2, 0, 2, 2,
       1, 2, 2, 2, 0, 2, 1, 2, 0, 0, 1, 2, 0, 2, 0, 2, 2, 0, 2, 2, 0, 0,
       1, 2, 1, 1, 0, 2, 2, 2, 0, 2, 0, 2, 2, 0, 2, 2, 0, 2, 2, 2, 0, 0,
       2, 2, 2, 2, 2, 2, 2, 0, 2, 2, 2, 2, 2, 2, 2, 2, 1, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 0, 0, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 1,
       2, 0, 2, 2, 0, 2, 1, 2, 0, 2, 2, 2, 0, 2, 2, 0, 1, 2, 0, 2, 0, 2,
       2, 2, 2, 0, 2, 2, 2, 0, 0, 2, 2, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 0, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 1, 2, 2, 0, 2,
       2, 0, 2, 2, 2, 0, 2, 2, 2, 2, 1, 2, 1, 2, 2, 2, 2, 2, 0, 0, 1, 2,
       1, 2, 2, 2, 2, 0, 2, 2, 2, 0, 1, 0, 2, 2, 2, 2, 1, 0, 2, 2, 0, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 0, 1,
       2, 2, 0, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 0, 0, 2, 0, 2, 1, 2, 2, 2,
       1, 2, 2, 2, 2, 2, 2, 2, 2, 0, 1, 2, 2, 2, 1, 2, 1, 2, 2, 2, 2, 0,
       2, 2, 2, 1, 2, 0, 0, 2, 2, 0, 0, 2, 2, 0, 1,

In [160]:
le_name = LabelEncoder()
le_fid.fit(data_X['Name'])
data_X['Name'] = le_fid.fit_transform(data_X['Name'])

In [161]:
le_sex = LabelEncoder()
le_fid.fit(data_X['Sex'])
data_X['Sex'] = le_fid.fit_transform(data_X['Sex'])

In [162]:
le_ticket = LabelEncoder()
le_fid.fit(data_X['Ticket'])
data_X['Ticket'] = le_fid.fit_transform(data_X['Ticket'])

In [163]:
le_cabin = LabelEncoder()
le_fid.fit(data_X['Cabin'])
data_X['Cabin'] = le_fid.fit_transform(data_X['Cabin'])

In [164]:
data_X

PassengerId  Survived  Pclass  Name  Sex        Age  SibSp  Parch  \
0              1         0       3   108    1  22.000000      1      0   
1              2         1       1   190    0  38.000000      1      0   
2              3         1       3   353    0  26.000000      0      0   
3              4         1       1   272    0  35.000000      1      0   
4              5         0       3    15    1  35.000000      0      0   
..           ...       ...     ...   ...  ...        ...    ...    ...   
886          887         0       2   548    1  27.000000      0      0   
887          888         1       1   303    0  19.000000      0      0   
888          889         0       3   413    0  29.699118      1      2   
889          890         1       1    81    1  26.000000      0      0   
890          891         0       3   220    1  32.000000      0      0   

     Ticket     Fare  Cabin  
0       523   7.2500     47  
1       596  71.2833     81  
2       669   7.9250     47  
3        49  53.1000     55  
4       472   8.0500     47  
..      ...      ...    ...  
886     101  13.0000     47  
887      14  30.0000     30  
888     675  23.4500     47  
889       8  30.0000     60  
890     466   7.7500     47  

[891 rows x 11 columns]

In [165]:
df2 = pd.DataFrame(data_X)


In [166]:
df2.to_csv(r'my_data.csv', index=False)

In [516]:
from sklearn.model_selection import train_test_split
X_train, X_test,y_train, y_test = train_test_split(data_X, data_y_trans, train_size = 0.7,random_state=67)

In [517]:
from sklearn.preprocessing import StandardScaler
ss = StandardScaler()
X_train_std = ss.fit_transform(X_train)
X_test_std = ss.fit_transform(X_test)

In [518]:
from sklearn.metrics import accuracy_score
from sklearn.metrics import classification_report
from sklearn.metrics import confusion_matrix

Decision Tree

In [519]:
from sklearn.tree import DecisionTreeClassifier
ml = DecisionTreeClassifier()


ml.fit(X_train_std,y_train)
res=ml.predict(X_test_std)


from sklearn.metrics import accuracy_score
accuracy_1=accuracy_score(y_test,res)
print("Decision tree :",accuracy_1*100)

Decision tree : 78.35820895522389


In [520]:
print("Classification Report for Decision Tree: \n", classification_report(le.inverse_transform(y_test), le.inverse_transform(res)))

Classification Report for Decision Tree: 
               precision    recall  f1-score   support

           C       0.67      0.72      0.69        53
           Q       0.42      0.65      0.51        20
           S       0.88      0.82      0.85       195

    accuracy                           0.78       268
   macro avg       0.66      0.73      0.68       268
weighted avg       0.81      0.78      0.79       268



In [521]:
rf_conf_mat = confusion_matrix(y_test, res)
print("Decision Tree: \n", rf_conf_mat)

Decision Tree: 
 [[ 38   1  14]
 [  0  13   7]
 [ 19  17 159]]


Random Forest

In [522]:
from sklearn.ensemble import RandomForestClassifier
rf1 = RandomForestClassifier()
rf1.fit(X_train_std, y_train)
rf_y_pred1 = rf1.predict(X_test_std)

acc_score1 = accuracy_score(y_test, rf_y_pred1)
print("Accuracy Score for Random_Forest: \n", acc_score1*100)

Accuracy Score for Random_Forest: 
 88.05970149253731


In [523]:
print("Classification Report for Random Forest: \n", classification_report(le.inverse_transform(y_test), le.inverse_transform(rf_y_pred1)))

Classification Report for Random Forest: 
               precision    recall  f1-score   support

           C       0.88      0.70      0.78        53
           Q       1.00      0.45      0.62        20
           S       0.88      0.97      0.92       195

    accuracy                           0.88       268
   macro avg       0.92      0.71      0.77       268
weighted avg       0.89      0.88      0.87       268



In [524]:
rf_conf_mat = confusion_matrix(y_test, rf_y_pred1)
print("Random Forest Confusion matrix: \n", rf_conf_mat)

Random Forest Confusion matrix: 
 [[ 37   0  16]
 [  0   9  11]
 [  5   0 190]]


Gradient Boosting

In [525]:
from sklearn.ensemble import GradientBoostingClassifier


gradient_boost1 = GradientBoostingClassifier()
gradient_boost1.fit(X_train_std, y_train)


res_xg1=gradient_boost1.predict(X_test_std)


acc_score_xg1 = accuracy_score(y_test, res_xg1)
print("Accuracy Score for GradientBoosting: \n", acc_score_xg1*100)

Accuracy Score for GradientBoosting: 
 88.43283582089553


In [526]:
print("Classification Report for Gradient Boosting: \n", classification_report(le.inverse_transform(y_test), le.inverse_transform(res_xg1)))

Classification Report for Gradient Boosting: 
               precision    recall  f1-score   support

           C       0.83      0.72      0.77        53
           Q       0.92      0.60      0.73        20
           S       0.89      0.96      0.93       195

    accuracy                           0.88       268
   macro avg       0.88      0.76      0.81       268
weighted avg       0.88      0.88      0.88       268



In [527]:
rf_conf_mat = confusion_matrix(y_test, res_xg1)
print("Gradient Boosting Confusion matrix: \n", rf_conf_mat)

Gradient Boosting Confusion matrix: 
 [[ 38   1  14]
 [  0  12   8]
 [  8   0 187]]


SVM

In [528]:
from sklearn.svm import SVC
from sklearn.metrics import accuracy_score


svm_classifier = SVC()
svm_classifier.fit(X_train_std, y_train)

res_svm = svm_classifier.predict(X_test_std)


acc_score_svm = accuracy_score(y_test, res_svm)
print("Accuracy Score for SVM: \n", acc_score_svm * 100)

Accuracy Score for SVM: 
 75.3731343283582


In [529]:
print("Classification Report for SVM: \n", classification_report(le.inverse_transform(y_test), le.inverse_transform(res_svm)))

Classification Report for SVM: 
               precision    recall  f1-score   support

           C       0.73      0.15      0.25        53
           Q       0.50      0.05      0.09        20
           S       0.76      0.99      0.86       195

    accuracy                           0.75       268
   macro avg       0.66      0.40      0.40       268
weighted avg       0.73      0.75      0.68       268



In [530]:
svm_conf_mat = confusion_matrix(y_test, res_svm)
print("SVM Confusion Matrix: \n", svm_conf_mat)

SVM Confusion Matrix: 
 [[  8   1  44]
 [  1   1  18]
 [  2   0 193]]
