<a href="https://colab.research.google.com/github/FathimaNazarudeen/Advanced-Computing-Lab/blob/main/project.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [50]:
import pandas as pd
import numpy as np

In [51]:
df=pd.read_csv("/content/train.csv")

In [53]:
df.dtypes

PassengerId      int64
Survived         int64
Pclass           int64
Name            object
Sex             object
Age            float64
SibSp            int64
Parch            int64
Ticket          object
Fare           float64
Cabin           object
Embarked        object
dtype: object

In [54]:
data_real = df.replace(np.inf, np.nan)


In [55]:
data_real.isnull().sum().sum()

866

In [56]:
data_df = data_real.dropna(axis=0)

In [57]:
data_df.isnull().sum().sum()

0

In [58]:
data_df

PassengerId  Survived  Pclass  \
1              2         1       1   
3              4         1       1   
6              7         0       1   
10            11         1       3   
11            12         1       1   
..           ...       ...     ...   
871          872         1       1   
872          873         0       1   
879          880         1       1   
887          888         1       1   
889          890         1       1   

                                                  Name     Sex   Age  SibSp  \
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
6                              McCarthy, Mr. Timothy J    male  54.0      0   
10                     Sandstrom, Miss. Marguerite Rut  female   4.0      1   
11                            Bonnell, Miss. Elizabeth  female  58.0      0   
..                                                 ...     ...   ...    ...   
871   Beckwith, Mrs. Richard Leonard (Sallie Monypeny)  female  47.0      1   
872                           Carlsson, Mr. Frans Olof    male  33.0      0   
879      Potter, Mrs. Thomas Jr (Lily Alexenia Wilson)  female  56.0      0   
887                       Graham, Miss. Margaret Edith  female  19.0      0   
889                              Behr, Mr. Karl Howell    male  26.0      0   

     Parch    Ticket     Fare        Cabin Embarked  
1        0  PC 17599  71.2833          C85        C  
3        0    113803  53.1000         C123        S  
6        0     17463  51.8625          E46        S  
10       1   PP 9549  16.7000           G6        S  
11       0    113783  26.5500         C103        S  
..     ...       ...      ...          ...      ...  
871      1     11751  52.5542          D35        S  
872      0       695   5.0000  B51 B53 B55        S  
879      1     11767  83.1583          C50        C  
887      0    112053  30.0000          B42        S  
889      0    111369  30.0000         C148        C  

[183 rows x 12 columns]

In [59]:
data_X = data_df.drop(['Embarked'], axis = 1)

In [60]:
data_y = data_df['Embarked']

Label encoding

In [61]:

from sklearn.preprocessing import LabelEncoder


le = LabelEncoder()

In [62]:
data_y_trans = le.fit_transform(data_y)
le_fid = LabelEncoder()

In [63]:
data_y_trans

array([0, 2, 2, 2, 2, 2, 2, 2, 0, 0, 2, 2, 2, 2, 2, 0, 0, 2, 2, 0, 2, 2,
       2, 2, 0, 2, 2, 2, 0, 0, 2, 2, 0, 0, 2, 0, 0, 0, 2, 2, 1, 2, 2, 2,
       2, 2, 2, 2, 2, 0, 2, 0, 0, 2, 0, 2, 0, 0, 0, 0, 2, 0, 0, 2, 0, 2,
       2, 2, 0, 2, 2, 2, 2, 2, 0, 0, 0, 0, 2, 0, 2, 1, 2, 2, 2, 2, 2, 2,
       2, 0, 0, 2, 2, 2, 0, 0, 2, 0, 2, 0, 2, 2, 0, 2, 2, 2, 2, 0, 2, 0,
       2, 0, 0, 0, 2, 2, 2, 2, 0, 0, 2, 0, 0, 0, 2, 2, 2, 2, 2, 2, 0, 0,
       0, 0, 0, 2, 2, 0, 0, 2, 2, 0, 2, 0, 2, 2, 0, 2, 2, 0, 2, 2, 2, 0,
       2, 0, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 0, 2, 2, 2, 2, 2, 2, 0, 2, 2,
       2, 2, 2, 2, 0, 2, 0])

In [70]:
le_name = LabelEncoder()
le_fid.fit(data_X['Name'])
data_X['Name'] = le_fid.fit_transform(data_X['Name'])

In [71]:
le_sex = LabelEncoder()
le_fid.fit(data_X['Sex'])
data_X['Sex'] = le_fid.fit_transform(data_X['Sex'])

In [72]:
le_ticket = LabelEncoder()
le_fid.fit(data_X['Ticket'])
data_X['Ticket'] = le_fid.fit_transform(data_X['Ticket'])

In [73]:
le_cabin = LabelEncoder()
le_fid.fit(data_X['Cabin'])
data_X['Cabin'] = le_fid.fit_transform(data_X['Cabin'])

In [75]:
data_X

PassengerId  Survived  Pclass  Name  Sex   Age  SibSp  Parch  Ticket  \
1              2         1       1    49    0  38.0      1      0     109   
3              4         1       1    70    0  35.0      1      0      31   
6              7         0       1   112    1  54.0      0      0      55   
10            11         1       3   148    0   4.0      1      1     120   
11            12         1       1    27    0  58.0      0      0      26   
..           ...       ...     ...   ...  ...   ...    ...    ...     ...   
871          872         1       1    18    0  47.0      1      1      33   
872          873         0       1    35    1  33.0      0      0      89   
879          880         1       1   140    0  56.0      0      1      38   
887          888         1       1    75    0  19.0      0      0      10   
889          890         1       1    20    1  26.0      0      0       8   

        Fare  Cabin  
1    71.2833     72  
3    53.1000     48  
6    51.8625    117  
10   16.7000    131  
11   26.5500     43  
..       ...    ...  
871  52.5542     91  
872   5.0000     29  
879  83.1583     61  
887  30.0000     25  
889  30.0000     52  

[183 rows x 11 columns]

In [76]:
df2 = pd.DataFrame(data_X)


In [77]:
df2.to_csv(r'my_data.csv', index=False)

In [103]:
from sklearn.model_selection import train_test_split
X_train, X_test,y_train, y_test = train_test_split(data_X, data_y_trans, train_size = 0.7,random_state = 50)

In [104]:
from sklearn.preprocessing import StandardScaler
ss = StandardScaler()
X_train_std = ss.fit_transform(X_train)
X_test_std = ss.fit_transform(X_test)

In [97]:
from sklearn.metrics import accuracy_score
from sklearn.metrics import classification_report
from sklearn.metrics import confusion_matrix

Decision Tree

In [105]:
from sklearn.tree import DecisionTreeClassifier
ml = DecisionTreeClassifier()


ml.fit(X_train_std,y_train)
res=ml.predict(X_test_std)


from sklearn.metrics import accuracy_score
accuracy_1=accuracy_score(y_test,res)
print("Decision tree :",accuracy_1*100)

Decision tree : 61.81818181818181


In [106]:
print("Classification Report for Decision Tree: \n", classification_report(le.inverse_transform(y_test), le.inverse_transform(res)))

Classification Report for Decision Tree: 
               precision    recall  f1-score   support

           C       0.71      0.40      0.51        25
           Q       0.00      0.00      0.00         2
           S       0.59      0.86      0.70        28

    accuracy                           0.62        55
   macro avg       0.43      0.42      0.40        55
weighted avg       0.62      0.62      0.59        55



/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


Random Forest

In [107]:

from sklearn.ensemble import RandomForestClassifier
rf1 = RandomForestClassifier()
rf1.fit(X_train_std, y_train)
rf_y_pred1 = rf1.predict(X_test_std)

acc_score1 = accuracy_score(y_test, rf_y_pred1)
print("Accuracy Score for Random_Forest: \n", acc_score1*100)

Accuracy Score for Random_Forest: 
 69.0909090909091


In [108]:
print("Classification Report for Random Forest: \n", classification_report(le.inverse_transform(y_test), le.inverse_transform(rf_y_pred1)))

Classification Report for Random Forest: 
               precision    recall  f1-score   support

           C       0.78      0.56      0.65        25
           Q       0.00      0.00      0.00         2
           S       0.65      0.86      0.74        28

    accuracy                           0.69        55
   macro avg       0.48      0.47      0.46        55
weighted avg       0.68      0.69      0.67        55



/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


Gradient Boosting

In [117]:
from sklearn.ensemble import GradientBoostingClassifier


gradient_boost1 = GradientBoostingClassifier()
gradient_boost1.fit(X_train_std, y_train)


res_xg1=gradient_boost1.predict(X_test_std)


acc_score_xg1 = accuracy_score(y_test, res_xg1)
print("Accuracy Score for GradientBoosting: \n", acc_score_xg1*100)

Accuracy Score for GradientBoosting: 
 60.0


In [118]:
print("Classification Report for Gradient Boosting: \n", classification_report(le.inverse_transform(y_test), le.inverse_transform(res_xg1)))

Classification Report for Gradient Boosting: 
               precision    recall  f1-score   support

           C       0.67      0.40      0.50        25
           Q       0.00      0.00      0.00         2
           S       0.57      0.82      0.68        28

    accuracy                           0.60        55
   macro avg       0.41      0.41      0.39        55
weighted avg       0.60      0.60      0.57        55



/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


SVM

In [111]:
from sklearn.svm import SVC
from sklearn.metrics import accuracy_score


svm_classifier = SVC()
svm_classifier.fit(X_train_std, y_train)

res_svm = svm_classifier.predict(X_test_std)


acc_score_svm = accuracy_score(y_test, res_svm)
print("Accuracy Score for SVM: \n", acc_score_svm * 100)

Accuracy Score for SVM: 
 54.54545454545454


In [112]:
print("Classification Report for SVM: \n", classification_report(le.inverse_transform(y_test), le.inverse_transform(res_svm)))

Classification Report for SVM: 
               precision    recall  f1-score   support

           C       0.56      0.20      0.29        25
           Q       0.00      0.00      0.00         2
           S       0.54      0.89      0.68        28

    accuracy                           0.55        55
   macro avg       0.37      0.36      0.32        55
weighted avg       0.53      0.55      0.48        55



/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [113]:
svm_conf_mat = confusion_matrix(y_test, res_svm)
print("SVM Confusion Matrix: \n", svm_conf_mat)

SVM Confusion Matrix: 
 [[ 5  0 20]
 [ 1  0  1]
 [ 3  0 25]]
