<a href="https://colab.research.google.com/github/FathimaNazarudeen/Advanced-Computing-Lab/blob/main/Experiment%2011/MLP_regressor.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
from sklearn.neural_network import MLPRegressor
from sklearn.datasets import make_regression


In [4]:
X, y = make_regression(n_samples=20, n_features=3, random_state=1)

In [12]:
import numpy
numpy.shape(X)

(20, 3)

In [13]:
y

array([  -7.00766922,  -23.32252002,   25.0705527 , -112.30734132,
         40.47679433,  -75.74394066,  -87.23159723,   38.65979395,
         86.37807751,   -6.20444587,  -84.33111343,   15.51804759,
        130.9822354 ,    4.31361666,  103.77692959,  113.07869181,
         27.42693388,  -65.30169504, -112.504787  ,  -30.92216021])

In [8]:
 from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y,random_state=1)

In [9]:
regr = MLPRegressor(random_state=1, max_iter=500).fit(X_train, y_train)

/usr/local/lib/python3.7/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:696: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  ConvergenceWarning,


In [10]:
regr.predict(X_test[:2])

array([-41.47721943,  24.19611808])

In [11]:
regr.score(X_test, y_test)

0.43065525958822237

In [14]:
y_pred=regr.predict(X_test)

In [15]:
y_pred

array([-41.47721943,  24.19611808, -36.35144933, -34.08581767,
        14.48195741])

In [16]:
from sklearn import metrics as m
print(m.r2_score(y_test,y_pred))

0.43065525958822237
